[package]
name = "hakanai-wasm"
version = "2.8.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "WASM module for Hakanai QR code generation"
repository = "https://github.com/czerwonk/hakanai"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
qrcode = "0.14"

