{{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not .Values.externalRedis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hakanai.fullname" . }}-redis-external
  labels:
    {{- include "hakanai.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}