name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update dependencies
        run: helm dependency update helm/hakanai

      - name: Package Helm chart
        run: |
          mkdir -p .charts-tmp
          helm package helm/hakanai -d .charts-tmp

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm repository
        run: |
          cp .charts-tmp/*.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://czerwonk.github.io/hakanai
          git add .
          git diff --staged --quiet || git commit -m "Update Helm chart to version $(helm show chart ../helm/hakanai | grep '^version:' | awk '{print $2}')"
          git push

  # Deploy GitHub Pages
  deploy-pages:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4