name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: tests/package-lock.json
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lld
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Ensure npm modules are installed
        run: npm install

      - name: Run clippy
        run: cargo clippy --workspace
