name: Publish to crates.io

on:
  push:
    tags:
      - "v*"

jobs:
  lint-check:
    uses: ./.github/workflows/lint.yml

  test-check:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: [build-check, lint-check, test-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify version matches tag
        run: |
          VERSION=$(grep '^version = ' lib/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Cargo.toml version: $VERSION"
          echo "Git tag version: $TAG_VERSION"
          if [ "$VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch! Cargo.toml has $VERSION but tag is $TAG_VERSION"
            exit 1
          fi

      - name: Publish hakanai-lib to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p hakanai-lib --token $CARGO_REGISTRY_TOKEN
