name: Publish to crates.io

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify version matches tag
        run: |
          VERSION=$(grep '^version = ' lib/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Cargo.toml version: $VERSION"
          echo "Git tag version: $TAG_VERSION"
          if [ "$VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch! Cargo.toml has $VERSION but tag is $TAG_VERSION"
            exit 1
          fi

      - name: Publish hakanai-lib to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p hakanai-lib --token $CARGO_REGISTRY_TOKEN

      - name: Publish hakanai-cli to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p hakanai --token $CARGO_REGISTRY_TOKEN
