name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-check:
    uses: ./.github/workflows/lint.yml

  test-check:
    uses: ./.github/workflows/test.yml

  precompile-assets:
    name: Pre-compile TypeScript and WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lld
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.1"
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Ensure npm modules are installed
        run: npm install

      - name: Compile WASM
        run: cd wasm && ./build.sh
      - name: Compile TypeScript
        run: npx rollup -c

      - name: Upload compiled assets
        uses: actions/upload-artifact@v4
        with:
          name: compiled-assets
          path: |
            server/src/includes/*.js
            server/src/includes/*.wasm

  build:
    name: Build - ${{ matrix.platform.release_for }}
    needs: [lint-check, test-check, precompile-assets]
    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: hakanai
            name: hakanai-darwin-x86_64.tar.gz
            command: build

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: hakanai
            name: hakanai-darwin-aarch64.tar.gz
            command: build

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: hakanai
            name: hakanai-linux-x86_64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download pre-compiled assets
        uses: actions/download-artifact@v4
        with:
          name: compiled-assets
          path: server/src/includes/

      - name: Set skip build flags
        run: |
          echo "SKIP_TYPESCRIPT_BUILD=1" >> $GITHUB_ENV
          echo "SKIP_WASM_BUILD=1" >> $GITHUB_ENV

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}

      - name: Build
        run: cargo build --release --workspace --target ${{ matrix.platform.target }}

      - name: Prepare artifacts [macOS/Linux]
        if: matrix.platform.os != 'windows-latest'
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.name }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
