name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Rust tests
        run: cargo test --verbose

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: tests/package-lock.json

      - name: Setup TypeScript
        run: npm install -g typescript

      - name: Build TypeScript client
        run: make build-ts

      - name: Install test dependencies
        run: npm ci
        working-directory: ./tests

      - name: Run TypeScript tests
        run: npm test
        working-directory: ./tests
